---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
"Beware the Jabberwock, my son!  
  The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
  The frumious Bandersnatch!"  
He took his vorpal sword in hand:
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
He was found by the Bureau of Statistics to be  
One against whom there was no official complaint,  
And all the reports on his conduct agree  
That, in the modern sense of an old-fashioned word, he was a saint,  
For in everything he did he served the Greater Community.  
Except for the War till the day he retired  
He worked in a factory and never got fired,  
But satisfied his employers, Fudge Motors Inc.  
Yet he wasn’t a scab or odd in his views,  
For his Union reports that he paid his dues,  
(Our report on his Union shows it was sound)  
And our Social Psychology workers found  
That he was popular with his mates and liked a drink.  
The Press are convinced that he bought a paper every day  
And that his reactions to advertisements were normal in every way.  
Policies taken out in his name prove that he was fully insured,  
And his Health-card shows he was once in hospital but left it cured.  
Both Producers Research and High-Grade Living declare  
He was fully sensible to the advantages of the Instalment Plan  
And had everything necessary to the Modern Man,  
A phonograph, a radio, a car and a frigidaire.  
Our researchers into Public Opinion are content  
That he held the proper opinions for the time of year;  
When there was peace, he was for peace:  when there was war, he went.  
He was married and added five children to the population,  
Which our Eugenist says was the right number for a parent of his generation.  
And our teachers report that he never interfered with their education.  
Was he free? Was he happy? The question is absurd:  
Had anything been wrong, we should certainly have heard.
<!--Put a short poem of your choice 8-20 lines,here!-->
